version: "3"

services:
    frontend:
      build: ./frontend
      ports:
        - 3000:3000
      volumes:
        - ./frontend:/usr/src/app
    backend:
      build: ./backend
      ports:
        - 4000:4000
      volumes:
        - ./backend:/usr/src/app
        - /usr/src/app/node_modules # anonymous volume for node_modules only
      env_file: 
        - dev.env
    db:
      image: mongo
      volumes: 
        - shanas-sourdough-db:/data/db

volumes:
  shanas-sourdough-db: