version: "3"

services:
    todo-frontend:
      build: ./todo-frontend
      ports:
        - 3000:3000
      volumes:
        - ./todo-frontend:/usr/src/app
    todo-backend:
      build: ./todo-backend
      ports:
        - 4000:4000
      volumes:
        - ./todo-backend:/usr/src/app
        - /usr/src/app/node_modules # anonymous volume for node_modules only
      env_file: 
        - dev.env
    todo-db:
      image: mongo
      volumes: 
        - todo-db:/data/db

volumes:
  todo-db: